### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Naimado6** [schorschii/OCO-Agent#11]
Hi, 
I have some issues with oco, i try to install a package on a computer (windows 11) but everytimes i try this it go to offline in the oco IT client manager and i can't install this package
Have you ever met this issue and do you have a solution ?

**Comment by schorschii** [comment]
It sounds like your package installation command does not come to an end. Please start the agent [on the command line](https://github.com/schorschii/OCO-Agent?tab=readme-ov-file#troubleshootingdebugging) before deploying the package and have a look at the output. Also, please provide your installation command here.

**Comment by Naimado6** [comment]
`GLPI-Agent-1.7-gitb7e81f7a-x64.msi /allusers /SILENT` this is the package i try to install and i start the agent on the command line but nothing has change.

**Comment by schorschii** [comment]
Of course, there are no functional changes when you execute it on the command line. You should have a look at the output or post it here for further analysis.

**Comment by schorschii** [comment]
`/allusers` is not a valid MSI parameter. What happens in the background is that this window opens and stays open forever, that's why the job never finishes.
![Bildschirmfoto vom 2023-12-19 16-38-15](https://github.com/schorschii/OCO-Agent/assets/17480795/37bdc1f6-d3da-4eb6-ae03-a52539fa8c98)

I recommend trying all package installation commands manually on a reference PC before using it via OCO.

What may works is `ALLUSERS=1` but this depends on the MSI package.

**Comment by Naimado6** [comment]
The installation of the packet works thanks to yours advice thanks a lot !!
